// Stamp the package with a hash of its own SOURCE, so a built artifact can be checked
// against the source it was built from.
//
// The failure this exists to make impossible: a measured arm runs a BUNDLE that embedded
// tierless at build time. Edit tierless, forget to rebuild, and the arm silently runs the
// OLD framework while every local check passes. It has happened three times — n8n's
// @n8n/rest-api-client dist (which voided a whole ablation), the gateway's compiled bin
// (a fixed regex that never reached the running gateway), and n8n's editor-ui bundle.
// Each cost a debugging session or a wasted measurement.
//
// Same discipline as ports/run.mts's treeHash: content identity, checked rather than
// assumed. ports/assert-fresh.mts is the consumer.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SRC = fileURLToPath(new URL("../src/", import.meta.url));
const STAMP = path.join(SRC, "build-stamp.mts");

/** sha256 over every .mts source, sorted by path — the stamp file itself excluded (it
 *  cannot contain its own hash). .mjs build outputs are excluded too: they are DERIVED,
 *  so including them would make the stamp depend on whether a build had already run. */
export function sourceHash() {
  const files = [];
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith(".mts") && p !== STAMP) files.push(p);
    }
  };
  walk(SRC);
  const h = createHash("sha256");
  for (const f of files.sort((a, b) => a.localeCompare(b, "en"))) {
    h.update(path.relative(SRC, f)); h.update("\0");
    h.update(readFileSync(f)); h.update("\0");
  }
  return h.digest("hex").slice(0, 16);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const hash = sourceHash();
  const body = `// GENERATED by scripts/stamp.mjs — do not edit; rewritten on every build.
// A hash of this package's own sources, embedded in anything that bundles tierless so a
// built artifact can be checked against the source it came from (ports/assert-fresh.mts).
export const TIERLESS_BUILD = ${JSON.stringify(hash)};
`;
  let prev = "";
  try { prev = readFileSync(STAMP, "utf8"); } catch { /* first run */ }
  if (prev !== body) {
    writeFileSync(STAMP, body);
    console.log(`tierless: build stamp ${hash}`);
  }
}
