import js from "@eslint/js";
import globals from "globals";

// Correctness-focused, not style-focused: Stackmix is deliberately written in a dense,
// single-line-per-opcode style, and reformatting it would hurt readability. ESLint here
// catches real mistakes (undefined names, accidental reassignments) and leaves the house
// style alone.
export default [
  {
    ignores: [
      "node_modules/**",
      // Compiler INPUTS (.src.js): plain developer code with free tier globals (api/commit) by design.
      "src/app/App.src.js",
      "src/cf-fixtures.src.js",
      "src/heap-app.src.js",
      "src/heap-auto.src.js",
      "src/heap-write.src.js",
      "src/policy-app.src.js",
      "src/track-app.src.js",
      "src/delta-app.src.js",
      "src/conduit/App.src.js",
      "bench/overhead.src.js",
      "bench/conduit.src.js",
      // Compiler OUTPUTS (.gen.mjs): generated by transform.cjs, not hand-edited.
      "src/app/bundle.gen.mjs",
      "src/cf-fixtures.gen.mjs",
      "src/heap-app.gen.mjs",
      "src/heap-auto.gen.mjs",
      "src/heap-write.gen.mjs",
      "src/policy-app.gen.mjs",
      "src/track-app.gen.mjs",
      "src/delta-app.gen.mjs",
      "src/conduit/bundle.gen.mjs",
      "bench/overhead.gen.mjs",
      "bench/conduit.gen.mjs",
      // The compiler itself: a CommonJS build tool that needs the Babel toolchain.
      "src/transform.cjs",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.mjs", "**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.es2021,
        WebSocket: "readonly",
      },
    },
    rules: {
      // unused locals are worth knowing about, but unused fn args (op handlers, callbacks)
      // are idiomatic here.
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      // `while (true) { ... }` is the pump's main loop and the migration oscillators.
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-cond-assign": ["error", "except-parens"],
    },
  },
  {
    // The browser tier runs in a real page (DOM, WebSocket, …).
    files: ["src/public/**/*.mjs"],
    languageOptions: { globals: { ...globals.browser } },
  },
];
