import js from "@eslint/js";
import globals from "globals";

// Correctness-focused, not style-focused: Stackmix is deliberately written in a dense,
// single-line-per-opcode style, and reformatting it would hurt readability. ESLint here
// catches real mistakes (undefined names, accidental reassignments) and leaves the house
// style alone.
export default [
  {
    ignores: [
      "node_modules/**",
      // Compiler INPUTS (.src.js): plain developer code with free tier globals (api/commit) by design.
      "demos/app/App.src.js",
      "demos/cf-fixtures.src.js",
      "demos/heap-app.src.js",
      "demos/heap-auto.src.js",
      "demos/heap-write.src.js",
      "demos/policy-app.src.js",
      "demos/track-app.src.js",
      "demos/delta-app.src.js",
      "demos/conduit/App.src.js",
      "demos/api-pump-app.src.js",
      "examples/*/src/actions.mjs",   // mix-module inputs: bare tier globals (api.*) by design
      "examples/*/dist/**",
      "packages/create-stackmix/template/app.src.js",   // compiler input: bare api/commit by design
      "bench/overhead.src.js",
      "bench/conduit.src.js",
      // Compiler OUTPUTS (.gen.mjs): generated by transform.cjs, not hand-edited.
      "demos/app/bundle.gen.mjs",
      "demos/cf-fixtures.gen.mjs",
      "demos/heap-app.gen.mjs",
      "demos/heap-auto.gen.mjs",
      "demos/heap-write.gen.mjs",
      "demos/policy-app.gen.mjs",
      "demos/track-app.gen.mjs",
      "demos/delta-app.gen.mjs",
      "demos/conduit/bundle.gen.mjs",
      "demos/api-pump-app.gen.mjs",
      "bench/overhead.gen.mjs",
      "bench/conduit.gen.mjs",
      // The compiler itself: a CommonJS build tool that needs the Babel toolchain.
      "packages/stackmix/src/transform.cjs",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.mjs", "**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.es2021,
        WebSocket: "readonly",
      },
    },
    rules: {
      // unused locals are worth knowing about, but unused fn args (op handlers, callbacks)
      // are idiomatic here.
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      // `while (true) { ... }` is the pump's main loop and the migration oscillators.
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-cond-assign": ["error", "except-parens"],
    },
  },
  {
    // The browser tier runs in a real page (DOM, WebSocket, …).
    files: ["demos/public/**/*.mjs", "packages/stackmix/src/browser.mjs", "packages/stackmix/src/react.mjs", "examples/**/*.mjs", "examples/**/*.jsx", "packages/create-stackmix/template/client.mjs"],
    languageOptions: { globals: { ...globals.browser } },
  },
  {
    // Example app JSX (espree parses JSX with the flag; the react plugin isn't needed for correctness
    // rules — PascalCase vars are components used by JSX, which core no-unused-vars can't see).
    files: ["examples/**/*.jsx"],
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    rules: { "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^[A-Z_]" }] },
  },
];
