import js from "@eslint/js";
import globals from "globals";

// Correctness-focused, not style-focused: Stackmix's interpreter is deliberately
// written in a dense, single-line-per-opcode style, and reformatting it would hurt
// readability. ESLint here catches real mistakes (undefined names, accidental
// reassignations) and leaves the house style alone.
export default [
  {
    ignores: [
      "node_modules/**",
      "**/*.ts",
      "**/*.wat",
      "**/*.wasm",
      "**/*.csv",
      "test/test262/vendor/**", // fetched Test262 corpus (not ours to lint)
      "experiments/qjs-migrate/qjsmig.mjs", // emscripten-generated glue
      "experiments/qjs-migrate/raw_lib.js", // emscripten --js-library (addToLibrary/Module globals)
      "experiments/react-tiers/app/App.src.js", // tier-split compiler INPUT (free globals by design)
      "experiments/react-tiers/cf-fixtures.src.js", // ditto: control-flow compiler INPUT
      "experiments/react-tiers/app/bundle.gen.mjs", // generated by transform.cjs
      "experiments/react-tiers/cf-fixtures.gen.mjs", // generated by transform.cjs
      "experiments/react-tiers/transform.cjs", // CommonJS build tool (needs the Babel toolchain)
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.mjs", "**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.es2021,
        WebAssembly: "readonly",
        performance: "readonly",
      },
    },
    rules: {
      // unused locals are worth knowing about, but unused fn args (interpreter
      // op handlers, callbacks) are idiomatic here.
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      // `while (true) { ... }` is the interpreter's main loop and the migration
      // oscillators — intentional.
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-cond-assign": ["error", "except-parens"],
    },
  },
  {
    // The live react-tiers demo's browser tier runs in a real page (DOM, WebSocket, …).
    files: ["experiments/react-tiers/public/**/*.mjs"],
    languageOptions: { globals: { ...globals.browser } },
  },
];
