// GENERATED by scripts/stamp.mjs — do not edit; rewritten on every build.
// A hash of this package's own sources, embedded in anything that bundles tierless so a
// built artifact can be checked against the source it came from (ports/assert-fresh.mts).
export const TIERLESS_BUILD = "5107ccb0f9b8d8ef";
