// GENERATED by transform.cjs from test/demos/cf-fixtures.src.js — do not edit by hand.

// --- suspensions in EXPRESSION positions (the compiler hoists them to temps) ---
function addPure(a, b) { return a + b; } // pure helper: emitted verbatim, called inline
export const PROGRAMS = {
  forContinue(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.i = 1;
        F.pc = 4; break;
      case 4:
        if (F.i <= 6) { F.pc = 10; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        // suspend inside the loop
F.sum = F.sum + F.x;
        F.pc = 5; break;
      case 7:
        F.x = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.dbl", args: [F.i] };
      case 9:
        F.pc = 5; break;
      case 10:
        if (F.i % 2 === 0) { F.pc = 9; } else { F.pc = 8; } break;
      case 11:
        F.sum = 0;
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in forContinue");
    }
  },
  whileBreak(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.acc };
      case 3:
        if (F.n < 100) { F.pc = 9; } else { F.pc = 2; } break;
      case 4:
        F.pc = 2; break;
      case 5:
        if (F.acc >= 10) { F.pc = 4; } else { F.pc = 3; } break;
      case 6:
        // suspend inside the loop
F.acc = F.acc + F.v;
        F.pc = 5; break;
      case 7:
        F.v = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.get", args: [F.n] };
      case 9:
        F.n = F.n + 1;
        F.pc = 8; break;
      case 10:
        F.acc = 0;
        F.pc = 3; break;
      case 11:
        F.n = 0;
        F.pc = 10; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in whileBreak");
    }
  },
  catchAcrossTier(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.r };
      case 3:
        (F.__h || (F.__h = [])).push({ catch: 4, fin: null, state: 0 }); F.pc = 8; break;
      case 4:
        F.e = F.__err;
        F.pc = 10; break;
      case 5:
        F.__h.pop();
        F.pc = 2; break;
      case 6:
        // the resource throws ON ITS TIER, across the suspend
F.r = "got:" + F.v;
        F.pc = 5; break;
      case 7:
        F.v = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.fail", args: [1] };
      case 9:
        F.__h.pop();
        F.pc = 2; break;
      case 10:
        F.r = "rescued:" + F.e.message; // ...and is caught here
        F.pc = 9; break;
      case 11:
        F.r = "start";
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in catchAcrossTier");
    }
  },
  finallyRuns(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 12; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.log };
      case 3:
        (F.__h || (F.__h = [])).push({ catch: null, fin: 4, state: 0 }); F.pc = 9; break;
      case 4:
        F.pc = 11; break;
      case 5:
        F.__h[F.__h.length - 1].state = 2;
        F.__c = null;
        F.pc = 4; break;
      case 6:
        // suspend inside try
F.log = F.log + F.v;
        F.pc = 5; break;
      case 7:
        F.v = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.get", args: [5] };
      case 9:
        F.log = F.log + "a";
        F.pc = 8; break;
      case 10:
        { F.__h.pop(); const __c = F.__c; if (!__c) { F.pc = 2; break; } if (__c.type === "throw") { F.__c = null; const __t = __dispatch(F, __c.arg); if (__t == null) return { op: "throw", value: __c.arg }; F.pc = __t; break; } const __p = __unwindStep(F); if (__p != null) { F.pc = __p; break; } F.__c = null; if (__c.type === "return") return { op: "return", value: __c.value }; F.pc = __c.target; break; }
      case 11:
        F.log = F.log + "F"; // runs on the normal path
        F.pc = 10; break;
      case 12:
        F.log = "";
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in finallyRuns");
    }
  },
  catchFinally(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 17; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.log };
      case 3:
        (F.__h || (F.__h = [])).push({ catch: null, fin: 4, state: 0 }); F.pc = 6; break;
      case 4:
        F.pc = 16; break;
      case 5:
        F.__h[F.__h.length - 1].state = 2;
        F.__c = null;
        F.pc = 4; break;
      case 6:
        (F.__h || (F.__h = [])).push({ catch: 7, fin: null, state: 0 }); F.pc = 12; break;
      case 7:
        F.e = F.__err;
        F.pc = 14; break;
      case 8:
        F.__h.pop();
        F.pc = 5; break;
      case 9:
        // throws across the suspend
F.log = F.log + F.v;
        F.pc = 8; break;
      case 10:
        F.v = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.fail", args: [1] };
      case 12:
        F.log = F.log + "a";
        F.pc = 11; break;
      case 13:
        F.__h.pop();
        F.pc = 5; break;
      case 14:
        F.log = F.log + "C"; // catch runs
        F.pc = 13; break;
      case 15:
        { F.__h.pop(); const __c = F.__c; if (!__c) { F.pc = 2; break; } if (__c.type === "throw") { F.__c = null; const __t = __dispatch(F, __c.arg); if (__t == null) return { op: "throw", value: __c.arg }; F.pc = __t; break; } const __p = __unwindStep(F); if (__p != null) { F.pc = __p; break; } F.__c = null; if (__c.type === "return") return { op: "return", value: __c.value }; F.pc = __c.target; break; }
      case 16:
        F.log = F.log + "F"; // then finally runs
        F.pc = 15; break;
      case 17:
        F.log = "";
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in catchFinally");
    }
  },
  fetchDouble(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 4; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.row + F.row };
      case 3:
        F.row = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "server", name: "api.get", args: [F.args[0]] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in fetchDouble");
    }
  },
  sumViaHelper(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 9; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.total };
      case 3:
        F.i = 1;
        F.pc = 4; break;
      case 4:
        if (F.i <= 3) { F.pc = 8; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        // CALL: push a sub-frame for fetchDouble, resume on return
F.total = F.total + F.r;
        F.pc = 5; break;
      case 7:
        F.r = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "call", fn: "fetchDouble", args: [F.i] };
      case 9:
        F.total = 0;
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in sumViaHelper");
    }
  },
  failingFetch(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 4; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.v };
      case 3:
        F.v = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "server", name: "api.fail", args: [1] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in failingFetch");
    }
  },
  callerCatches(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.r };
      case 3:
        (F.__h || (F.__h = [])).push({ catch: 4, fin: null, state: 0 }); F.pc = 8; break;
      case 4:
        F.e = F.__err;
        F.pc = 10; break;
      case 5:
        F.__h.pop();
        F.pc = 2; break;
      case 6:
        // the callee's resource error...
F.r = "ok:" + F.v;
        F.pc = 5; break;
      case 7:
        F.v = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "call", fn: "failingFetch", args: [] };
      case 9:
        F.__h.pop();
        F.pc = 2; break;
      case 10:
        F.r = "caught:" + F.e.message; // ...is caught here, one frame up
        F.pc = 9; break;
      case 11:
        F.r = "start";
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in callerCatches");
    }
  },
  throwInMachine(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.out };
      case 3:
        (F.__h || (F.__h = [])).push({ catch: 4, fin: null, state: 0 }); F.pc = 7; break;
      case 4:
        F.e = F.__err;
        F.pc = 9; break;
      case 5:
        F.__h.pop();
        F.pc = 2; break;
      case 6:
        { const __t = __dispatch(F, "boom"); if (__t == null) return { op: "throw", value: "boom" }; F.pc = __t; break; }
      case 7:
        F.out = "in";
        F.pc = 6; break;
      case 8:
        F.__h.pop();
        F.pc = 2; break;
      case 9:
        F.out = "caught:" + F.e;
        F.pc = 8; break;
      case 10:
        F.out = F.ret;
        F.pc = 3; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.get", args: [1] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in throwInMachine");
    }
  },
  returnExpr(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 4; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.__t0 + 1 };
      case 3:
        F.__t0 = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "server", name: "api.get", args: [7] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in returnExpr");
    }
  },
  assignRhs(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 6; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.out };
      case 3:
        F.out = F.__t0; // resource on an assignment RHS -> hoisted
        F.pc = 2; break;
      case 4:
        F.__t0 = F.ret;
        F.pc = 3; break;
      case 5:
        F.pc = 4; return { op: "resource", tier: "server", name: "api.get", args: [5] };
      case 6:
        F.out = "a";
        F.pc = 5; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in assignRhs");
    }
  },
  ifTest(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 6; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: "no" };
      case 3:
        return { op: "return", value: "yes" };
      case 4:
        if (F.__t0) { F.pc = 3; } else { F.pc = 2; } break;
      case 5:
        F.__t0 = F.ret;
        F.pc = 4; break;
      case 6:
        F.pc = 5; return { op: "resource", tier: "server", name: "api.get", args: [1] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in ifTest");
    }
  },
  whileTestSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.pc = 9; break;
      case 4:
        F.i = F.i - 1;
        F.pc = 3; break;
      case 5:
        // resource in a while-test -> desugared (re-evaluated each pass)
F.sum = F.sum + F.i;
        F.pc = 4; break;
      case 6:
        F.pc = 2; break;
      case 7:
        if (!F.__t0) { F.pc = 6; } else { F.pc = 5; } break;
      case 8:
        F.__t0 = F.ret;
        F.pc = 7; break;
      case 9:
        F.pc = 8; return { op: "resource", tier: "server", name: "api.dec", args: [F.i] };
      case 10:
        F.sum = 0;
        F.pc = 3; break;
      case 11:
        F.i = 3;
        F.pc = 10; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in whileTestSusp");
    }
  },
  nestedArgs(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 6; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: addPure(F.__t0, F.__t1) };
      case 3:
        F.__t1 = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "server", name: "api.get", args: [3] };
      case 5:
        F.__t0 = F.ret;
        F.pc = 4; break;
      case 6:
        F.pc = 5; return { op: "resource", tier: "server", name: "api.get", args: [2] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in nestedArgs");
    }
  },
  callInExpr(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 4; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.__t0 + 1 };
      case 3:
        F.__t0 = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "call", fn: "fetchDouble", args: [4] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in callInExpr");
    }
  },
  ternaryPick(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 11; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.x };
      case 3:
        F.x = F.__t0; // ?: — only the taken branch suspends (lowered to if/else)
        F.pc = 2; break;
      case 4:
        F.__t0 = F.__t1;
        F.pc = 3; break;
      case 5:
        F.__t1 = F.ret;
        F.pc = 4; break;
      case 6:
        F.pc = 5; return { op: "resource", tier: "server", name: "api.get", args: [7] };
      case 7:
        F.__t0 = F.__t2;
        F.pc = 3; break;
      case 8:
        F.__t2 = F.ret;
        F.pc = 7; break;
      case 9:
        F.pc = 8; return { op: "resource", tier: "server", name: "api.get", args: [9] };
      case 10:
        if (F.hi) { F.pc = 6; } else { F.pc = 9; } break;
      case 11:
        F.hi = 1;
        F.pc = 10; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in ternaryPick");
    }
  },
  shortCircuit(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 15; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.a + F.b };
      case 3:
        // || right side suspends
F.b = F.__t1; // && short-circuits: api.fail never runs
        F.pc = 2; break;
      case 4:
        F.__t1 = F.__t3;
        F.pc = 3; break;
      case 5:
        F.__t3 = F.ret;
        F.pc = 4; break;
      case 6:
        F.pc = 5; return { op: "resource", tier: "server", name: "api.fail", args: [1] };
      case 7:
        if (F.__t1) { F.pc = 6; } else { F.pc = 3; } break;
      case 8:
        F.__t1 = F.off;
        F.pc = 7; break;
      case 9:
        F.a = F.__t0; // || right side suspends
        F.pc = 8; break;
      case 10:
        F.__t0 = F.__t2;
        F.pc = 9; break;
      case 11:
        F.__t2 = F.ret;
        F.pc = 10; break;
      case 12:
        F.pc = 11; return { op: "resource", tier: "server", name: "api.get", args: [5] };
      case 13:
        if (!F.__t0) { F.pc = 12; } else { F.pc = 9; } break;
      case 14:
        F.__t0 = F.off;
        F.pc = 13; break;
      case 15:
        F.off = 0;
        F.pc = 14; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in shortCircuit");
    }
  },
  switchPick(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 17; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.out };
      case 3:
        F.out = F.__t2;
        F.pc = 2; break;
      case 4:
        F.__t2 = F.ret;
        F.pc = 3; break;
      case 5:
        F.pc = 4; return { op: "resource", tier: "server", name: "api.get", args: [0] };
      case 6:
        F.pc = 2; break;
      case 7:
        F.out = F.__t1;
        F.pc = 6; break;
      case 8:
        F.__t1 = F.ret;
        F.pc = 7; break;
      case 9:
        F.pc = 8; return { op: "resource", tier: "server", name: "api.get", args: [20] };
      case 10:
        F.pc = 2; break;
      case 11:
        F.out = F.__t0;
        F.pc = 10; break;
      case 12:
        F.__t0 = F.ret;
        F.pc = 11; break;
      case 13:
        F.pc = 12; return { op: "resource", tier: "server", name: "api.get", args: [10] };
      case 14:
        if (F.k === 2) { F.pc = 9; } else { F.pc = 5; } break;
      case 15:
        if (F.k === 1) { F.pc = 13; } else { F.pc = 14; } break;
      case 16:
        F.out = "none";
        F.pc = 15; break;
      case 17:
        F.k = 2;
        F.pc = 16; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in switchPick");
    }
  },
  switchFall(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 17; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.acc };
      case 3:
        F.acc = F.acc + F.__t2;
        F.pc = 2; break;
      case 4:
        F.__t2 = F.ret;
        F.pc = 3; break;
      case 5:
        F.pc = 4; return { op: "resource", tier: "server", name: "api.get", args: [3] };
      case 6:
        F.pc = 2; break;
      case 7:
        F.acc = F.acc + F.__t1;
        F.pc = 6; break;
      case 8:
        F.__t1 = F.ret;
        F.pc = 7; break;
      case 9:
        F.pc = 8; return { op: "resource", tier: "server", name: "api.get", args: [2] };
      case 10:
        F.acc = F.acc + F.__t0;
        F.pc = 9; break;
      case 11:
        F.__t0 = F.ret;
        F.pc = 10; break;
      case 12:
        F.pc = 11; return { op: "resource", tier: "server", name: "api.get", args: [1] };
      case 13:
        if (F.k === 3) { F.pc = 5; } else { F.pc = 2; } break;
      case 14:
        if (F.k === 2) { F.pc = 9; } else { F.pc = 13; } break;
      case 15:
        if (F.k === 1) { F.pc = 12; } else { F.pc = 14; } break;
      case 16:
        F.acc = 0;
        F.pc = 15; break;
      case 17:
        F.k = 1;
        F.pc = 16; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in switchFall");
    }
  },
  labeledBreak(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 14; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.found };
      case 3:
        F.i = 1;
        F.pc = 4; break;
      case 4:
        if (F.i <= 3) { F.pc = 6; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        F.j = 1;
        F.pc = 7; break;
      case 7:
        if (F.j <= 3) { F.pc = 13; } else { F.pc = 5; } break;
      case 8:
        F.j = F.j + 1;
        F.pc = 7; break;
      case 9:
        F.pc = 2; break;
      case 10:
        F.found = F.v;
        F.pc = 9; break;
      case 11:
        if (F.v === 4) { F.pc = 10; } else { F.pc = 8; } break;
      case 12:
        F.v = F.ret;
        F.pc = 11; break;
      case 13:
        F.pc = 12; return { op: "resource", tier: "server", name: "api.get", args: [F.i * F.j] };
      case 14:
        F.found = 0;
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in labeledBreak");
    }
  },
  doWhileSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 10; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.pc = 8; break;
      case 4:
        if (F.i < 3) { F.pc = 3; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        // suspends in a do-while body
F.sum = F.sum + F.v;
        F.pc = 5; break;
      case 7:
        F.v = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.get", args: [F.i] };
      case 9:
        F.sum = 0;
        F.pc = 3; break;
      case 10:
        F.i = 0;
        F.pc = 9; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in doWhileSusp");
    }
  },
  forHeaderSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 9; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.pc = 4; break;
      case 4:
        if (F.i <= 3) { F.pc = 6; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        // suspending for-init -> hoisted before the loop
F.sum = F.sum + F.i;
        F.pc = 5; break;
      case 7:
        F.i = F.ret;
        F.pc = 3; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.get", args: [1] };
      case 9:
        F.sum = 0;
        F.pc = 8; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in forHeaderSusp");
    }
  },
  returnInTry(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 2; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        (F.__h || (F.__h = [])).push({ catch: 3, fin: null, state: 0 }); F.pc = 7; break;
      case 3:
        F.e = F.__err;
        F.pc = 9; break;
      case 4:
        F.__h.pop();
        F.pc = 1; break;
      case 5:
        F.__h.pop();
        return { op: "return", value: F.v };
      case 6:
        F.v = F.ret;
        F.pc = 5; break;
      case 7:
        F.pc = 6; return { op: "resource", tier: "server", name: "api.get", args: [5] };
      case 8:
        F.__h.pop();
        F.pc = 1; break;
      case 9:
        F.__h.pop();
        return { op: "return", value: -1 };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in returnInTry");
    }
  },
  breakOutOfTry(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 16; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.i = 1;
        F.pc = 4; break;
      case 4:
        if (F.i <= 5) { F.pc = 6; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        (F.__h || (F.__h = [])).push({ catch: 7, fin: null, state: 0 }); F.pc = 13; break;
      case 7:
        F.e = F.__err;
        F.pc = 15; break;
      case 8:
        F.__h.pop();
        F.pc = 5; break;
      case 9:
        // break crosses the try (pops its handler)
F.sum = F.sum + F.v;
        F.pc = 8; break;
      case 10:
        F.__h.pop();
        F.pc = 2; break;
      case 11:
        if (F.v === 3) { F.pc = 10; } else { F.pc = 9; } break;
      case 12:
        F.v = F.ret;
        F.pc = 11; break;
      case 13:
        F.pc = 12; return { op: "resource", tier: "server", name: "api.get", args: [F.i] };
      case 14:
        F.__h.pop();
        F.pc = 5; break;
      case 15:
        F.sum = -1;
        F.pc = 14; break;
      case 16:
        F.sum = 0;
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in breakOutOfTry");
    }
  },
  returnThroughFinally(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 12; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        (F.__h || (F.__h = [])).push({ catch: null, fin: 3, state: 0 }); F.pc = 7; break;
      case 3:
        F.pc = 11; break;
      case 4:
        F.__h[F.__h.length - 1].state = 2;
        F.__c = null;
        F.pc = 3; break;
      case 5:
        F.__c = { type: "return", value: F.v, steps: [{ fin: 3 }] }; { const __p = __unwindStep(F); if (__p != null) { F.pc = __p; break; } const __c = F.__c; F.__c = null; return { op: "return", value: __c.value }; }
      case 6:
        F.v = F.ret;
        F.pc = 5; break;
      case 7:
        F.pc = 6; return { op: "resource", tier: "server", name: "api.get", args: [7] };
      case 8:
        { F.__h.pop(); const __c = F.__c; if (!__c) { F.pc = 1; break; } if (__c.type === "throw") { F.__c = null; const __t = __dispatch(F, __c.arg); if (__t == null) return { op: "throw", value: __c.arg }; F.pc = __t; break; } const __p = __unwindStep(F); if (__p != null) { F.pc = __p; break; } F.__c = null; if (__c.type === "return") return { op: "return", value: __c.value }; F.pc = __c.target; break; }
      case 9:
        F.log = F.__t0; // finally runs (and may itself suspend) — does not change the return
        F.pc = 8; break;
      case 10:
        F.__t0 = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.get", args: [1] };
      case 12:
        F.log = 0;
        F.pc = 2; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in returnThroughFinally");
    }
  },
  forUpdateSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 14; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.pc = 11; break;
      case 4:
        // suspending for-update (runs each pass, continue still hits it)
F.sum = F.sum + F.i;
        F.pc = 3; break;
      case 5:
        F.pc = 2; break;
      case 6:
        if (!(F.i <= 3)) { F.pc = 5; } else { F.pc = 4; } break;
      case 7:
        F.__t0 = false;
        F.pc = 6; break;
      case 8:
        F.i = F.__t1;
        F.pc = 6; break;
      case 9:
        if (F.__t0) { F.pc = 7; } else { F.pc = 8; } break;
      case 10:
        F.__t1 = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.inc", args: [F.i] };
      case 12:
        F.__t0 = true;
        F.pc = 3; break;
      case 13:
        F.i = 1;
        F.pc = 12; break;
      case 14:
        F.sum = 0;
        F.pc = 13; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in forUpdateSusp");
    }
  },
  doWhileTestSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 16; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.pc = 13; break;
      case 4:
        F.i = F.i + 1;
        F.pc = 3; break;
      case 5:
        F.sum = F.sum + F.i;
        F.pc = 4; break;
      case 6:
        F.__t0 = false;
        F.pc = 5; break;
      case 7:
        F.pc = 2; break;
      case 8:
        if (!F.__t1) { F.pc = 7; } else { F.pc = 6; } break;
      case 9:
        F.__t1 = F.__t2;
        F.pc = 8; break;
      case 10:
        F.__t2 = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.lt3", args: [F.i] };
      case 12:
        if (!F.__t1) { F.pc = 11; } else { F.pc = 8; } break;
      case 13:
        F.__t1 = F.__t0;
        F.pc = 12; break;
      case 14:
        F.__t0 = true;
        F.pc = 3; break;
      case 15:
        F.sum = 0;
        F.pc = 14; break;
      case 16:
        F.i = 0;
        F.pc = 15; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in doWhileTestSusp");
    }
  },
  unbracedBranchSusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 15; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.out };
      case 3:
        F.out = F.__t0;
        F.pc = 2; break;
      case 4:
        F.__t0 = F.ret;
        F.pc = 3; break;
      case 5:
        F.pc = 4; return { op: "resource", tier: "server", name: "api.get", args: [10] };
      case 6:
        F.out = F.__t1;
        F.pc = 2; break;
      case 7:
        F.__t1 = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.fail", args: [99] };
      case 9:
        F.out = F.__t2;
        F.pc = 2; break;
      case 10:
        F.__t2 = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "server", name: "api.get", args: [30] };
      case 12:
        if (F.route === "b") { F.pc = 8; } else { F.pc = 11; } break;
      case 13:
        if (F.route === "a") { F.pc = 5; } else { F.pc = 12; } break;
      case 14:
        F.out = 0;
        F.pc = 13; break;
      case 15:
        F.route = "a";
        F.pc = 14; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in unbracedBranchSusp");
    }
  },
  unbracedLoopBodySusp(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 10; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.sum };
      case 3:
        F.i = 0;
        F.pc = 4; break;
      case 4:
        if (F.i < 3) { F.pc = 9; } else { F.pc = 2; } break;
      case 5:
        F.i = F.i + 1;
        F.pc = 4; break;
      case 6:
        F.sum = F.sum + F.__t0;
        F.pc = 5; break;
      case 7:
        F.__t0 = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.get", args: [100] };
      case 9:
        if (F.i === 1) { F.pc = 8; } else { F.pc = 5; } break;
      case 10:
        F.sum = 0;
        F.pc = 3; break;
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in unbracedLoopBodySusp");
    }
  }
};

// A §5 handle — a big local that stayed on its owning tier (see ../heap.mjs). With
// --auto-deref the machine guards reads of remotable locals with this check.
export const isHandle = (x) => x !== null && typeof x === "object" && x.__stackmix_handle__ === true;
// Exception dispatch over the serializable handler stack F.__h. Returns the pc of the
// catch/finally to enter, or null if the throw escapes this frame. Called from the
// machine (for `throw`) and from the runtime (when a migrated resource throws).
export function __dispatch(F, err) {
  const hs = F.__h;
  while (hs && hs.length) {
    const h = hs[hs.length - 1];
    if (h.catch != null && h.state === 0) { h.state = 1; F.__err = err; return h.catch; }  // enter catch (handler stays for a wrapping finally)
    if (h.fin != null && h.state < 2) { h.state = 2; F.__c = { type: "throw", arg: err }; return h.fin; }
    hs.pop();
  }
  return null;
}
// Drive a pending return/break/continue (F.__c) through the finallys it must still run:
// pop the handlers of crossed try/catch regions, then return the next finally pc (or null
// when none remain and the completion should execute).
export function __unwindStep(F) {
  const c = F.__c; if (!c || !c.steps) return null;
  while (c.steps.length && c.steps[0].pop !== undefined) { for (let i = 0; i < c.steps[0].pop; i++) F.__h.pop(); c.steps.shift(); }
  if (c.steps.length) return c.steps.shift().fin;
  return null;
}
// Unwind an error across FRAMES: try the top frame's handlers, else pop it and try the
// caller. A resource that fails in a callee is thus caught by a try/catch in a caller.
export function __unwind(stack, err) {
  while (stack.length) { const tpc = __dispatch(stack[stack.length - 1], err); if (tpc != null) { stack[stack.length - 1].pc = tpc; return true; } stack.pop(); }
  return false;
}
// Single-tier driver: step the machine, push sub-frames for calls, stop at every resource
// request. The two-tier runtime (../runtime.mjs) drives PROGRAMS directly and only stops
// at resources THIS tier doesn't own; this local driver keeps the bundle runnable alone.
export function run(stack) {
  for (;;) {
    const top = stack[stack.length - 1];
    const r = PROGRAMS[top.fn](top);
    if (r.op === "return") { stack.pop(); if (!stack.length) return { done: true, value: r.value }; stack[stack.length - 1].ret = r.value; }
    else if (r.op === "call") { stack.push({ fn: r.fn, pc: 0, args: r.args }); }
    else if (r.op === "throw") { stack.pop(); if (!__unwind(stack, r.value)) throw r.value; }
    else if (r.op === "resource") return { done: false, request: r, stack };
  }
}
export const start = (fn, args = []) => run([{ fn, pc: 0, args }]);
