// GENERATED by transform.cjs from test/demos/heap-write.src.js — do not edit by hand.

export const PROGRAMS = {
  Edit(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 17; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.rows[F.ev.idx].score };
      case 3:
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "@writeback", name: "writeback", args: [F.rows] };
      case 5:
        // migrate to the browser; `rows` stays home as a handle
F.rows[F.ev.idx].score = F.ev.score; // browser edits a row -> auto-deref fetches, auto-writeback propagates back
        F.pc = 4; break;
      case 6:
        F.rows = F.__t1;
        F.pc = 5; break;
      case 7:
        F.__t1 = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "@deref", name: "deref", args: [F.rows] };
      case 9:
        if (isHandle(F.rows)) { F.pc = 8; } else { F.pc = 5; } break;
      case 10:
        F.ev = F.ret;
        F.pc = 9; break;
      case 11:
        F.pc = 10; return { op: "resource", tier: "browser", name: "dom.commit", args: [{ count: F.rows.length }] };
      case 12:
        F.rows = F.__t0;
        F.pc = 11; break;
      case 13:
        F.__t0 = F.ret;
        F.pc = 12; break;
      case 14:
        F.pc = 13; return { op: "resource", tier: "@deref", name: "deref", args: [F.rows] };
      case 15:
        if (isHandle(F.rows)) { F.pc = 14; } else { F.pc = 11; } break;
      case 16:
        F.rows = F.ret;
        F.pc = 15; break;
      case 17:
        F.pc = 16; return { op: "resource", tier: "server", name: "api.getRows", args: [] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in Edit");
    }
  }
};

// A §5 handle — a big local that stayed on its owning tier (see ../heap.mjs). With
// --auto-deref the machine guards reads of remotable locals with this check.
export const isHandle = (x) => x !== null && typeof x === "object" && x.__stackmix_handle__ === true;
// Exception dispatch over the serializable handler stack F.__h. Returns the pc of the
// catch/finally to enter, or null if the throw escapes this frame. Called from the
// machine (for `throw`) and from the runtime (when a migrated resource throws).
export function __dispatch(F, err) {
  const hs = F.__h;
  while (hs && hs.length) {
    const h = hs[hs.length - 1];
    if (h.catch != null && h.state === 0) { h.state = 1; F.__err = err; return h.catch; }  // enter catch (handler stays for a wrapping finally)
    if (h.fin != null && h.state < 2) { h.state = 2; F.__c = { type: "throw", arg: err }; return h.fin; }
    hs.pop();
  }
  return null;
}
// Drive a pending return/break/continue (F.__c) through the finallys it must still run:
// pop the handlers of crossed try/catch regions, then return the next finally pc (or null
// when none remain and the completion should execute).
export function __unwindStep(F) {
  const c = F.__c; if (!c || !c.steps) return null;
  while (c.steps.length && c.steps[0].pop !== undefined) { for (let i = 0; i < c.steps[0].pop; i++) F.__h.pop(); c.steps.shift(); }
  if (c.steps.length) return c.steps.shift().fin;
  return null;
}
// Unwind an error across FRAMES: try the top frame's handlers, else pop it and try the
// caller. A resource that fails in a callee is thus caught by a try/catch in a caller.
export function __unwind(stack, err) {
  while (stack.length) { const tpc = __dispatch(stack[stack.length - 1], err); if (tpc != null) { stack[stack.length - 1].pc = tpc; return true; } stack.pop(); }
  return false;
}
// Single-tier driver: step the machine, push sub-frames for calls, stop at every resource
// request. The two-tier runtime (../runtime.mjs) drives PROGRAMS directly and only stops
// at resources THIS tier doesn't own; this local driver keeps the bundle runnable alone.
export function run(stack) {
  for (;;) {
    const top = stack[stack.length - 1];
    const r = PROGRAMS[top.fn](top);
    if (r.op === "return") { stack.pop(); if (!stack.length) return { done: true, value: r.value }; stack[stack.length - 1].ret = r.value; }
    else if (r.op === "call") { stack.push({ fn: r.fn, pc: 0, args: r.args }); }
    else if (r.op === "throw") { stack.pop(); if (!__unwind(stack, r.value)) throw r.value; }
    else if (r.op === "resource") return { done: false, request: r, stack };
  }
}
export const start = (fn, args = []) => run([{ fn, pc: 0, args }]);
