// The corpus harness as a Playwright --config WRAPPER (docs/corpus.md test
// accommodations): the target suite runs through its own config, imported and
// re-anchored, with the transport-agnostic waits patched into its own playwright-core
// Page class and the measure reporter attached from the tierless package by absolute
// path. The target tree stays PRISTINE — no test patches, no dependency link. Grounded
// in what every corpus target actually has: a Playwright suite with a config file.
//
// Playwright loads the config in the runner AND in every worker process, so the class
// patch reaches every page of every worker; TIERLESS_WS_URL (shaped runs) rides an
// init script into each context as the adapt-auto localStorage override.
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const TIERLESS_SRC = fileURLToPath(new URL("../packages/tierless/src", import.meta.url));

/** Write the wrapper config for a suite; pass the returned path as `--config`. */
export function writeSuiteConfig({ suiteDir, outFile, configFile = "playwright.config.ts" }: { suiteDir: string; outFile: string; configFile?: string }): string {
  const content = `// GENERATED by ports/pw-wrapper.mts — do not edit; regenerated per run.
import base from ${JSON.stringify(path.join(suiteDir, configFile))};
const T = require(${JSON.stringify(path.join(TIERLESS_SRC, "playwright.mjs"))});
T.patchPlaywrightPages(T.resolveSuitePlaywright(${JSON.stringify(suiteDir)}), {
  initScript: process.env.TIERLESS_WS_URL
    ? "localStorage.setItem('tierlessWsUrl', " + JSON.stringify(process.env.TIERLESS_WS_URL) + ")"
    : undefined,
});
const anchored = T.anchorPlaywrightConfig(base, ${JSON.stringify(suiteDir)});
export default {
  ...anchored,
  ...(process.env.TIERLESS_MEASURE_OUT ? { reporter: [["line"], [${JSON.stringify(path.join(TIERLESS_SRC, "playwright-reporter.mjs"))}]] } : {}),
  use: { ...anchored.use, ...(process.env.BASE_URL ? { baseURL: process.env.BASE_URL } : {}) },
};
`;
  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, content);
  return outFile;
}
