// GENERATED by transform.cjs from src/delta-app.src.js — do not edit by hand.

let __DSINK = null;
export const __setDirtySink = (fn) => { const prev = __DSINK; __DSINK = fn || null; return prev; };
const __dirty = (o) => { if (__DSINK !== null && o !== null && typeof o === "object") __DSINK(o); return o; };
export const PROGRAMS = {
  Board(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 25; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.model.hops };
      case 3:
        if (F.catalog !== null) { F.pc = 22; } else { F.pc = 2; } break;
      case 4:
        F.pc = 2; break;
      case 5:
        if (F.ev.done) { F.pc = 4; } else { F.pc = 3; } break;
      case 6:
        // BROWSER resource — bounce; render + interaction
__dirty(F.model.log).push(F.ev.note); // array mutator (on the browser side)
        F.pc = 5; break;
      case 7:
        F.ev = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "browser", name: "dom.commit", args: [F.model] };
      case 9:
        // array mutator
__dirty(F.model.byId).set(F.data.id, F.row); // Map mutator
        F.pc = 8; break;
      case 10:
        __dirty(F.model.rows).push(F.row); // array mutator
        F.pc = 9; break;
      case 11:
        F.row = { id: F.data.id, label: F.data.label, hot: false };
        F.pc = 10; break;
      case 12:
        __dirty(F.model.rows[F.data.idx]).hot = true; // deep member assignment
        F.pc = 8; break;
      case 13:
        __dirty(F.model.rows[F.data.idx]).label = F.data.label; // deep member assignment
        F.pc = 8; break;
      case 14:
        if (F.data.kind === "label") { F.pc = 13; } else { F.pc = 8; } break;
      case 15:
        if (F.data.kind === "heat") { F.pc = 12; } else { F.pc = 14; } break;
      case 16:
        if (F.data.kind === "add") { F.pc = 11; } else { F.pc = 15; } break;
      case 17:
        __dirty(F.model).cursor = F.data.cursor;
        F.pc = 16; break;
      case 18:
        __dirty(F.model).hops = F.model.hops + 1;
        F.pc = 17; break;
      case 19:
        F.pc = 2; break;
      case 20:
        if (F.data.stop) { F.pc = 19; } else { F.pc = 18; } break;
      case 21:
        F.data = F.ret;
        F.pc = 20; break;
      case 22:
        F.pc = 21; return { op: "resource", tier: "server", name: "api.poll", args: [F.model.cursor] };
      case 23:
        // big reference dataset, fetched once — its OWN local, so it
F.model = { rows: [], log: [], hops: 0, cursor: 0, byId: new Map() }; // excises to a §5 handle and stays home
        F.pc = 3; break;
      case 24:
        F.catalog = F.ret;
        F.pc = 23; break;
      case 25:
        F.pc = 24; return { op: "resource", tier: "server", name: "api.getCatalog", args: [] };
      default: throw new RangeError("stackmix: invalid pc " + F.pc + " in Board (forged continuation?)");
    }
  }
};

// A §5 handle — a big local that stayed on its owning tier (see ../heap.mjs). With
// --auto-deref the machine guards reads of remotable locals with this check.
export const isHandle = (x) => x !== null && typeof x === "object" && x.__stackmix_handle__ === true;
// Exception dispatch over the serializable handler stack F.__h. Returns the pc of the
// catch/finally to enter, or null if the throw escapes this frame. Called from the
// machine (for `throw`) and from the runtime (when a migrated resource throws).
export function __dispatch(F, err) {
  const hs = F.__h;
  while (hs && hs.length) {
    const h = hs[hs.length - 1];
    if (h.catch != null && h.state === 0) { h.state = 1; F.__err = err; return h.catch; }  // enter catch (handler stays for a wrapping finally)
    if (h.fin != null && h.state < 2) { h.state = 2; F.__c = { type: "throw", arg: err }; return h.fin; }
    hs.pop();
  }
  return null;
}
// Drive a pending return/break/continue (F.__c) through the finallys it must still run:
// pop the handlers of crossed try/catch regions, then return the next finally pc (or null
// when none remain and the completion should execute).
export function __unwindStep(F) {
  const c = F.__c; if (!c || !c.steps) return null;
  while (c.steps.length && c.steps[0].pop !== undefined) { for (let i = 0; i < c.steps[0].pop; i++) F.__h.pop(); c.steps.shift(); }
  if (c.steps.length) return c.steps.shift().fin;
  return null;
}
// Unwind an error across FRAMES: try the top frame's handlers, else pop it and try the
// caller. A resource that fails in a callee is thus caught by a try/catch in a caller.
export function __unwind(stack, err) {
  while (stack.length) { const tpc = __dispatch(stack[stack.length - 1], err); if (tpc != null) { stack[stack.length - 1].pc = tpc; return true; } stack.pop(); }
  return false;
}
// Single-tier driver: step the machine, push sub-frames for calls, stop at every resource
// request. The two-tier runtime (../runtime.mjs) drives PROGRAMS directly and only stops
// at resources THIS tier doesn't own; this local driver keeps the bundle runnable alone.
export function run(stack) {
  for (;;) {
    const top = stack[stack.length - 1];
    const r = PROGRAMS[top.fn](top);
    if (r.op === "return") { stack.pop(); if (!stack.length) return { done: true, value: r.value }; stack[stack.length - 1].ret = r.value; }
    else if (r.op === "call") { stack.push({ fn: r.fn, pc: 0, args: r.args }); }
    else if (r.op === "throw") { stack.pop(); if (!__unwind(stack, r.value)) throw r.value; }
    else if (r.op === "resource") return { done: false, request: r, stack };
  }
}
export const start = (fn, args = []) => run([{ fn, pc: 0, args }]);
