// GENERATED by transform.cjs from track-app.src.js — do not edit by hand.

let __DSINK = null;
export const __setDirtySink = (fn) => { const prev = __DSINK; __DSINK = fn || null; return prev; };
const __dirty = (o) => { if (__DSINK !== null && o !== null && typeof o === "object") __DSINK(o); return o; };
// Plain source for the --track-writes proof: an oscillating session that MUTATES its continuation
// IN PLACE on every hop — there is not a single touch()/writeBack()/deref() here. The model object
// is created once and kept across hops (stable identity), and each event edits it: a field update,
// a deep member assignment, and array mutators. Compiled with --track-writes the compiler wraps each
// of those mutations in __dirty(obj), so the delta wire's write-tracked mode ships only the changed
// objects with no graph re-hash. commit() suspends each hop, making the continuation cross the tier
// boundary repeatedly — the exact oscillation delta encoding is for.
//
//   node transform.cjs track-app.src.js track-app.gen.mjs --bare --track-writes
//
// touchCount is a PURE (non-suspendable) helper that mutates an EXISTING continuation object passed
// across the call boundary — proving the compiler instruments pure helpers too, so an in-place edit
// inside one is not silently missed (it bumps the object the same way).
function touchCount(item) { __dirty(item).touches = (item.touches || 0) + 1; // in-place mutation of a caller-owned object
}
export const PROGRAMS = {
  Session(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 22; break;
      case 1:
        return { op: "return", value: "(end)" };
      case 2:
        return { op: "return", value: F.model.hops };
      case 3:
        F.pc = 21; break;
      case 4:
        __dirty(F.model.items).push({ id: F.ev.id, label: F.ev.label, done: false }); // array mutator (push)
        F.pc = 3; break;
      case 5:
        // deep member assignment
touchCount(F.model.items[F.ev.idx]); // mutation through a pure helper
        F.pc = 3; break;
      case 6:
        __dirty(F.model.items[F.ev.idx]).done = !F.model.items[F.ev.idx].done; // deep member assignment
        F.pc = 5; break;
      case 7:
        // deep member assignment
touchCount(F.model.items[F.ev.idx]); // mutation through a pure helper
        F.pc = 3; break;
      case 8:
        __dirty(F.model.items[F.ev.idx]).label = F.ev.label; // deep member assignment
        F.pc = 7; break;
      case 9:
        __dirty(F.model.log).push("tick " + F.model.hops); // array mutator on a different object
        F.pc = 3; break;
      case 10:
        __dirty(F.model.items).splice(0, F.model.items.length); // array mutator (splice)
        F.pc = 3; break;
      case 11:
        if (F.ev.type === "clear") { F.pc = 10; } else { F.pc = 3; } break;
      case 12:
        if (F.ev.type === "tick") { F.pc = 9; } else { F.pc = 11; } break;
      case 13:
        if (F.ev.type === "rename") { F.pc = 8; } else { F.pc = 12; } break;
      case 14:
        if (F.ev.type === "toggle") { F.pc = 6; } else { F.pc = 13; } break;
      case 15:
        if (F.ev.type === "add") { F.pc = 4; } else { F.pc = 14; } break;
      case 16:
        // field update (assignment through a local)
__dirty(F.model).last = F.ev.type;
        F.pc = 15; break;
      case 17:
        __dirty(F.model).hops = F.model.hops + 1; // field update (assignment through a local)
        F.pc = 16; break;
      case 18:
        F.pc = 2; break;
      case 19:
        if (F.ev.type === "stop") { F.pc = 18; } else { F.pc = 17; } break;
      case 20:
        F.ev = F.ret;
        F.pc = 19; break;
      case 21:
        F.pc = 20; return { op: "resource", tier: "browser", name: "dom.commit", args: [F.model] };
      case 22:
        F.model = { items: [], log: [], hops: 0, last: null };
        F.pc = 3; break;
    }
  }
};

// A §5 handle — a big local that stayed on its owning tier (see ../heap.mjs). With
// --auto-deref the machine guards reads of remotable locals with this check.
export const isHandle = (x) => x !== null && typeof x === "object" && x.__stackmix_handle__ === true;
// Exception dispatch over the serializable handler stack F.__h. Returns the pc of the
// catch/finally to enter, or null if the throw escapes this frame. Called from the
// machine (for `throw`) and from the runtime (when a migrated resource throws).
export function __dispatch(F, err) {
  const hs = F.__h;
  while (hs && hs.length) {
    const h = hs[hs.length - 1];
    if (h.catch != null && h.state === 0) { h.state = 1; F.__err = err; return h.catch; }  // enter catch (handler stays for a wrapping finally)
    if (h.fin != null && h.state < 2) { h.state = 2; F.__c = { type: "throw", arg: err }; return h.fin; }
    hs.pop();
  }
  return null;
}
// Drive a pending return/break/continue (F.__c) through the finallys it must still run:
// pop the handlers of crossed try/catch regions, then return the next finally pc (or null
// when none remain and the completion should execute).
export function __unwindStep(F) {
  const c = F.__c; if (!c || !c.steps) return null;
  while (c.steps.length && c.steps[0].pop !== undefined) { for (let i = 0; i < c.steps[0].pop; i++) F.__h.pop(); c.steps.shift(); }
  if (c.steps.length) return c.steps.shift().fin;
  return null;
}
// Unwind an error across FRAMES: try the top frame's handlers, else pop it and try the
// caller. A resource that fails in a callee is thus caught by a try/catch in a caller.
export function __unwind(stack, err) {
  while (stack.length) { const tpc = __dispatch(stack[stack.length - 1], err); if (tpc != null) { stack[stack.length - 1].pc = tpc; return true; } stack.pop(); }
  return false;
}
// Single-tier driver: step the machine, push sub-frames for calls, stop at every resource
// request. The two-tier runtime (../runtime.mjs) drives PROGRAMS directly and only stops
// at resources THIS tier doesn't own; this local driver keeps the bundle runnable alone.
export function run(stack) {
  for (;;) {
    const top = stack[stack.length - 1];
    const r = PROGRAMS[top.fn](top);
    if (r.op === "return") { stack.pop(); if (!stack.length) return { done: true, value: r.value }; stack[stack.length - 1].ret = r.value; }
    else if (r.op === "call") { stack.push({ fn: r.fn, pc: 0, args: r.args }); }
    else if (r.op === "throw") { stack.pop(); if (!__unwind(stack, r.value)) throw r.value; }
    else if (r.op === "resource") return { done: false, request: r, stack };
  }
}
export const start = (fn, args = []) => run([{ fn, pc: 0, args }]);
