// GENERATED by transform.cjs from test/e2e/trio-app.src.js — do not edit by hand.

// The trajectory fixture: a working set, then THREE sequential server data resources.
// Sized so that at EVERY hop fetch is locally cheaper than migrating (the greedy §6 rule
// fetches three times) — yet one migration at the first hop serves B and C inline on the
// server and beats the greedy total. The information that flips hop A ("two more server
// resources follow") exists only in a trace of a prior run; no per-hop comparison can
// recover it. Each fetched result also lands in the frame, so the continuation grows with
// every fetch — greedy digs itself deeper with each locally-correct choice.
//
//   node transform.cjs trio-app.src.js trio-app.gen.mjs --bare
function build(n) { let work = []; for (let i = 0; i < n; i = i + 1) { work[i] = "row-" + i; } // pure: stays a plain local in Trio's frame
return work; }
export const PROGRAMS = {
  Trio(F) {
    while (true) switch (F.pc) {
      case 0:
        F.pc = 9; break;
      case 1:
        return { op: "return", value: undefined };
      case 2:
        return { op: "return", value: { work: F.work.length, a: F.a.length, b: F.b.length, c: F.c.length } };
      case 3:
        F.c = F.ret;
        F.pc = 2; break;
      case 4:
        F.pc = 3; return { op: "resource", tier: "server", name: "api.fetchC", args: [F.args[1]] };
      case 5:
        F.b = F.ret;
        F.pc = 4; break;
      case 6:
        F.pc = 5; return { op: "resource", tier: "server", name: "api.fetchB", args: [F.args[1]] };
      case 7:
        F.a = F.ret;
        F.pc = 6; break;
      case 8:
        F.pc = 7; return { op: "resource", tier: "server", name: "api.fetchA", args: [F.args[1]] };
      case 9:
        F.work = build(F.args[0]); // the live working set — sets the CONTINUATION (migrate) cost
        F.pc = 8; break;
      default: throw new RangeError("tierless: invalid pc " + F.pc + " in Trio");
    }
  }
};

// A §5 handle — a big local that stayed on its owning tier (see ../heap.mjs). With
// --auto-deref the machine guards reads of remotable locals with this check.
export const isHandle = (x) => x !== null && typeof x === "object" && x.__tierless_handle__ === true;
// Exception dispatch over the serializable handler stack F.__h. Returns the pc of the
// catch/finally to enter, or null if the throw escapes this frame. Called from the
// machine (for `throw`) and from the runtime (when a migrated resource throws).
export function __dispatch(F, err) {
  const hs = F.__h;
  while (hs && hs.length) {
    const h = hs[hs.length - 1];
    if (h.catch != null && h.state === 0) { h.state = 1; F.__err = err; return h.catch; }  // enter catch (handler stays for a wrapping finally)
    if (h.fin != null && h.state < 2) { h.state = 2; F.__c = { type: "throw", arg: err }; return h.fin; }
    hs.pop();
  }
  return null;
}
// Drive a pending return/break/continue (F.__c) through the finallys it must still run:
// pop the handlers of crossed try/catch regions, then return the next finally pc (or null
// when none remain and the completion should execute).
export function __unwindStep(F) {
  const c = F.__c; if (!c || !c.steps) return null;
  while (c.steps.length && c.steps[0].pop !== undefined) { for (let i = 0; i < c.steps[0].pop; i++) F.__h.pop(); c.steps.shift(); }
  if (c.steps.length) return c.steps.shift().fin;
  return null;
}
// Unwind an error across FRAMES: try the top frame's handlers, else pop it and try the
// caller. A resource that fails in a callee is thus caught by a try/catch in a caller.
export function __unwind(stack, err) {
  while (stack.length) { const tpc = __dispatch(stack[stack.length - 1], err); if (tpc != null) { stack[stack.length - 1].pc = tpc; return true; } stack.pop(); }
  return false;
}
// Single-tier driver: step the machine, push sub-frames for calls, stop at every resource
// request. The two-tier runtime (../runtime.mjs) drives PROGRAMS directly and only stops
// at resources THIS tier doesn't own; this local driver keeps the bundle runnable alone.
export function run(stack) {
  for (;;) {
    const top = stack[stack.length - 1];
    const r = PROGRAMS[top.fn](top);
    if (r.op === "return") { stack.pop(); if (!stack.length) return { done: true, value: r.value }; stack[stack.length - 1].ret = r.value; }
    else if (r.op === "call") { stack.push({ fn: r.fn, pc: 0, args: r.args }); }
    else if (r.op === "throw") { stack.pop(); if (!__unwind(stack, r.value)) throw r.value; }
    else if (r.op === "resource") return { done: false, request: r, stack };
  }
}
export const start = (fn, args = []) => run([{ fn, pc: 0, args }]);
export const BUNDLE_HASH = "d338bdff";
